### ISSUE TITLE
Pose composition error

### ISSUE THREAD

**Issue by elisabeth-ms** [mrpt-ros-pkg/pose_cov_ops#7]
Hi all!

I would like to use the pose_cov_ops package for transforming poses with uncertainty. However, I'm struggling with some problems with the pose composition function (pose_cov_ops::compose). 

For example, if you take a look at the attached picture. I'm trying to get the pose with uncertainty of test_gpr1_measure_wrt_gpr1 with respect to drill_head frame. For that I compose the pose of gpr1 with respect to the drill head frame and the pose of the  test_gpr1_measure_wrt_gpr1 with respect to gpr1. The purple ellipsoid displays the result of the composition with respect to the drill head. Although the result is not correct, the ellipsoid should be centered in the test_gpr1_measure_wrt_gpr frame, but it appears in other pose.

![image](https://user-images.githubusercontent.com/25179082/71256547-57b3eb00-2331-11ea-8063-f03a1d294699.png)

I add also the numbers:
Pose of the gpr1 with respect to drill head:  Position  (X:-0.333330 Y: -0.000002 Z: 0.100000) Orientation: (X: 0.707107 Y: -0.000000 Z: 0.707107 W: -0.000005)

Pose of test_gpr1_measure_wrt_gpr1 with respect to gpr1: Position (X: 1.435644 Y: 0.000000 Z: 0.000000) Orientation: (X:1.000000 Y: 0.000000 Z: 0.000000 W: 0.000000)

Result of the composition: Position (X: -0.333330 Y: -0.000002 Z: -1.335644) Orientation: (X: 0.000005 Y: 0.707107 Z: -0.000005 W: 0.707107)

Many thanks in advance

**Comment by jlblancoc** [comment]
Weird... I'll try to reproduce. 
What version of the package are you using? (i.e. installed via APT, what version of mrpt if built from sources, etc.)

**Comment by elisabeth-ms** [comment]
I'm using the version of the master branch of this repo with ROS kinetic and Ubuntu 16.04. Regarding the mrpt version, I'm also using the one in the master branch in https://github.com/MRPT/mrpt.

Thank you!

**Comment by jlblancoc** [comment]
I added a tiny unit test to the repo to debug your case. 
I think the problem is here:

> Pose of the gpr1 with respect to drill head: Position (X:-0.333330 Y: -0.000002 Z: 0.100000) Orientation: (X: 0.707107 Y: -0.000000 Z: 0.707107 W: -0.000005)

When I convert that quaternion to a SO(3) rotation matrix (using `mrpt_bridge`), I have the following CPose3D:

```
a: [-0.333330 0.000000 0.100000 179.999190 90.000000 0.000000]
Rot:
-6.12323e-17 -1.41421e-05           -1
 8.65956e-22           -1  1.41421e-05
          -1            0  6.12323e-17
```

which does NOT match the TFs in your picture: note how the first column of R (=the X axis of gpr1 wrt drill_head) is (0 0 -1), so the +X of this relative pose points like -Z in the base frame (drill_head), while it's the opposite in your picture. 

Could you please double check if that quaternion is correct? It might be a bug in mrpt's conversion from quaternion to rotation matrix, but I think that part is covered with unit tests... In any case, let me  know what you find. Cheers.

**Comment by elisabeth-ms** [comment]
Yes, the quaternion is correct.

Many thanks.

**Comment by jlblancoc** [comment]
Please, update mrpt_bridge and rebuild, the problem should be fixed now. 

It turned out that, apparently, ROS does not always gives quaternions with a non-negative real part, which breaks that assumption in MRPT code. 
Additional fixes have been pushed to MRPT/develop branch, but just updating the ROS package mrpt_bridge should be enough. 
Please, let us know if that fixes the issue.

**Comment by elisabeth-ms** [comment]
I hace updated the mrpt_bridge and also mrpt, although I'm still having the same problem.

**Comment by jlblancoc** [comment]
Hmmm... could you please write a tiny test case to demonstrate and keep debugging the issue? 

Just a minimal ROS package with a .cpp file that builds some ROS quaternion data, calls pose_cov_ops, and shows to screen the wrong result.

**Comment by elisabeth-ms** [comment]
I wrote a ROS node with some poses that uses pose_cov_ops for computing the composition.
https://github.com/elisabeth-ms/test_pose_cov_ops.git

**Comment by jlblancoc** [comment]
Ok, @elisabeth-ms , we found the error inside mrpt-math! Thanks for reporting. 
We'll release the fix soon to mrpt/develop.

**Comment by jlblancoc** [comment]
@elisabeth-ms please, check if the error is fixed after the commit referenced above to mrpt/develop, and report back if it's still present.
